function Data = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  UNTITLED = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  UNTITLED = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  Untitled = importfile("C:\Users\simol\OneDrive\Documenti\GitHub\FisMedLab\Silici\2.80.Spe", [13, 2060]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 01-Dec-2022 17:23:55

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [13, 2060];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["Counts", "Var2", "Var3", "Var4", "Var5"];
opts.SelectedVariableNames = "Counts";
opts.VariableTypes = ["double", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Specify variable properties
opts = setvaropts(opts, ["Var2", "Var3", "Var4", "Var5"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var2", "Var3", "Var4", "Var5"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "Counts", "TrimNonNumeric", true);
opts = setvaropts(opts, "Counts", "ThousandsSeparator", ",");

% Import the data
Data = readtable(filename, opts);

end