function [fitresult, gof] = createFit(V, I, x_BD, y_lim)
%CREATEFIT(V,I)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: V
%      Y Output: I
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 10-Dec-2022 16:18:34


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( V, I );

% Set up fittype and options.
ft = fittype( 'exp(a*x+b)+c*(x-d)^2', 'independent', 'x', 'dependent', 'y' );
excludedPoints = xData < x_BD;
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [1 1 1 1];
opts.Exclude = excludedPoints;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'Fit' );
h = plot( fitresult, xData, yData, excludedPoints );
legend( h, 'Data', 'Excluded data', 'Model fit', 'Location', 'NorthWest', 'Interpreter', 'none' );
% Label axes
xlabel( 'V', 'Interpreter', 'none' );
xlim([0 60])
ylabel( 'I', 'Interpreter', 'none' );
ylim([0 y_lim])
grid on

V_BD = fitresult.d




