function [fitresult, gof] = createFit(V, I, w)
%CREATEFIT(V,I,W)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: V
%      Y Output: I
%      Weights: w
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 27-Nov-2022 23:11:17


%% Fit: 'untitled fit 1'.
[xData, yData, weights] = prepareCurveData( V, I, w );

% Set up fittype and options.
ft = fittype( 'poly1' );
excludedPoints = xData < 0.7;
opts = fitoptions( 'Method', 'LinearLeastSquares' );
opts.Weights = weights;
opts.Exclude = excludedPoints;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Create a figure for the fit.
figure( 'Name', 'Fit' );

% Plot fit with data.
h = plot( fitresult, xData, yData, excludedPoints );
hold on
err = (1./w).^2;
errorbar(V, I, err, "LineStyle", "none", "Color", "black");
hold off
legend( h, 'Data', 'Excluded data', 'Fit', 'Location', 'NorthWest', 'Interpreter', 'none' );
% Label axes
title('I-V Curve (Direct Bias)');
xlabel( 'Voltage[V]', 'Interpreter', 'none' );
ylabel( 'Current[nA]', 'Interpreter', 'none' );
grid on

% Create a figure for the residuals.
figure( 'Name', 'Residuals' );

% Plot residuals.
h = plot( fitresult, xData, yData, excludedPoints, 'residuals' );
legend( h, 'Residuals', 'Excluded residuals', 'Zero Line', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
title('Residuals');
xlabel( 'Voltage[V]', 'Interpreter', 'none' );
ylabel( 'Current[nA]', 'Interpreter', 'none' );
grid on

disp('Fit Results')
disp(fitresult)

disp('Goodness of Fit')
disp(gof)

disp('Threshold Voltage')
x = fzero(fitresult,0)

ci = confint(fitresult);
m_error = (ci(2,1)-ci(1,1)) / (2)
q_error = (ci(2,2)-ci(1,2)) / (2)

end


